export const ADD_SOURCE = 'ADD_SOURCE';
export const DELETE_SOURCE = 'DELETE_SOURCE';
export const SELECT_SOURCE = 'SELECT_SOURCE';
export const SET_SELECTED_SOURCE = 'SET_SELECTED_SOURCE';

export const FETCH_FEED_REQUEST = 'FETCH_FEED_REQUEST';
export const FETCH_FEED_FAILURE = 'FETCH_FEED_FAILURE';
export const FETCH_FEED_SUCCESS = 'FETCH_FEED_SUCCESS';
